### PR TITLE
If the single worker raises an exception, ensure that it is released

### PR DESCRIPTION
**Pull request by theo-lanman**
@Tapjoy/eng-group-services 
cc @StabbyCutyou 

We got another bad job file—and no more work was being processed, without error. This addresses that issue.

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
You could drop line 29 if you wanna get picky, but otherwise I see the problem here. Lgtm.

**Comment by obrie** [comment]
What happens in this scenario:
* Who catch and rescues the exception?
* Do filesystem jobs get recovered (i.e. made new again)?

**Comment by StabbyCutyou** [comment]
The implementation in the forked worker is a little more thorough, but it's basically doing the same things here as far as I can see.

The worker bombing out because of exceptions should and re-trying the job should be handled elsewhere from what I remember.

**Comment by obrie** [comment]
I had looked through the code and it wasn't obvious to me how this was being handled.  I'd like to make sure we look through the code and understand / test the behavior.  Whoever looks at it, please post references to lines of code that accomplish proper recovery.

**Comment by StabbyCutyou** [comment]
Jobs that fail should be handled by the worker.rb itself (the base one in lib, not the strategies), but that brings up a good point - how did a crash in the worker itself bubble up to this point, when it should be handled by the worker itself to make sure the jobs get re-enqueued? Perhaps there are exceptions in worker.rb we're not accounting for?

**Comment by theo-lanman** [comment]
An exception in `SingleWorkerStrategy#assign` is caught [here](https://github.com/Tapjoy/chore/blob/master/lib/chore/queues/filesystem/consumer.rb#L97). This causes the (consumer) batch being worked on to be abandoned in the `inprogress` directory, and the next batch will be attempted. Nothing is recovered.

It looks like the unaccounted-for exception that happened in this case is unique to the batched worker—the regular worker [catches this](https://github.com/Tapjoy/chore/blob/master/lib/chore/worker.rb#L59). It still abandons the job, but not the whole batch.

The right solution here is probably to log errors and recover as gracefully as possible in the non-batched worker—as it is, any error that bubbles up to here will cause all further processing to halt without any alert—but the solution for the batched worker is a little more involved.

**Comment by theo-lanman** [comment]
Added some logging and cleaned this up a bit.

**Comment by StabbyCutyou** [comment]
If something does re-enter this by accident, would the @worker=nil line break anything?

Just wanna make sure we've thought the ensure block all the way through, but in general I think this is probably better than nothing either way.

**Comment by theo-lanman** [comment]
It sure would. How does this look?

**Comment by StabbyCutyou** [comment]
Much safer :)

If this works and you're happy with it, LGTM

**Pull request merged**
