### PR TITLE
After fork hook

### PR DESCRIPTION
**Pull request by goose42**
Adding an after fork hook to the pre-forked worker.

@riteshnoronha @obrie @StabbyCutyou @Ceraunograph

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
Makes sense

**Comment by riteshnoronha** [comment]
@goose42 can we audit any other hooks that we missed ?

**Comment by goose42** [comment]
@riteshnoronha yeah, working on that list.

**Comment by goose42** [comment]
Looks like we missed these hooks for the pre-forked worker: `around_fork`, `within_fork`, `after_fork`, `before_fork_shutdown`. The absent hooks will be added with a later PR (currently we only use the `after_fork`).

**Comment by riteshnoronha** [comment]
@goose42 this works. I verified this in production. However we should review all other hooks, since it appears that worker objects are being passed around and used in plugins.. which is not really ideal.. 

lgtm

**Pull request merged**
