### PR TITLE
Enable travis CI testing

### PR DESCRIPTION
**Pull request by goose42**
Adding a .travis.yml file to enable tests to run via Travis CI.

For review: @maudineormsby @andyleclair

### CODE REVIEW

**Comment by andyleclair** [comment]
@goose42 can you push another dummy commit? I think I have travis configured correctly, but it won't trigger until there's another commit pushed

**Comment by andyleclair** [comment]
Now it's running!

**Comment by andyleclair** [comment]
@goose42 There's a spec failure there, can you look into that?

**Comment by andyleclair** [comment]
You should add a couple of things here to speed up the spec runs:

```
git:
  depth: 10
```
Only check out the last 10 commits, so we don't have to clone the whole git history

```
cache:
  - bundle
```
So Travis can keep the bundle around, and only reinstall if the bundle changes

**Comment by goose42** [comment]
@andyleclair Specs should be fixed now. Also updated the travis config to speed up spec runs.

**Comment by andyleclair** [comment]
ooh baby that's the good stuff.

LGTM

**Pull request merged**
