### PR TITLE
Recover incomplete files for filesystem consumer at startup

### PR DESCRIPTION
**Pull request by obrie**
Initial spike of the implementation.  This hasn't been tested nor have specs been added, however specs do currently pass.  Looking for early feedback on approach.

/to @StabbyCutyou @theo-lanman 
/cc @Tapjoy/eng-group-services

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
Any specs for the FSQ itself to verify cleanup works?

**Comment by obrie** [comment]
Yep, yep.  Working on it.  You never read my PR descriptions do you? :stuck_out_tongue:

**Comment by StabbyCutyou** [comment]
They have descriptions in PRs now?

(It's a fair criticism - I almost always immediately jump into the code first, it's a bad habit).

**Comment by obrie** [comment]
Specs added

Ping @StabbyCutyou

**Comment by StabbyCutyou** [comment]
Seems pretty reasonable. I'm comfortable with these changes

**Comment by obrie** [comment]
This has been verified.  Squashing and merging.

**Pull request merged**
