### PR TITLE
Add profiler

### PR DESCRIPTION
**Pull request by theo-lanman**
@Tapjoy/eng-group-services 

__DO NOT MERGE__

Here's the profiling code for Chore.

This includes a pre-release version tag. This will evaluate as an "earlier" version than 1.8.0, so this should be safe to build as a gem.

Does this look safe to build and run in production?

### CODE REVIEW

**Comment by gregorysabatino** [comment]
LGTM

**Comment by obrie** [comment]
Could we just add this to our app and have the Procfile reference our version of the binary?  I don't know if that'd be any easier than messing with the chore version.

Otherwise feel free to integrate this as a gem.

**Comment by obrie** [comment]
(last statement should have included an lgtm)

**Comment by theo-lanman** [comment]
Good idea about including it in the sidecar. Doing that.

**Pull request closed without merging**
